### ISSUE TITLE
Name Control ASPXGRIDVIEW

### ISSUE THREAD

**Issue by rcerebro** [DevExpress-Examples/bootstrapchart-how-to-bind-to-filtered-or-sorted-aspxgridview-data-on-the-server-side-at-r-t556711#1]
Change name ASPxGridView for ASPxGridView1 to work correcty

c#
BootstrapChartDataItem[] BootstrapChartDataItems = new BootstrapChartDataItem[ASPxGridView1.VisibleRowCount];

for (int i = 0; i < ASPxGridView1.VisibleRowCount; i++)

gridDataRow = (ASPxGridView1.GetRow(i) as DataRowView).Row;

Asp.net
  <dx:ASPxGridView ID="ASPxGridView1" runat="server" DataSourceID="sqlDataSource" OnDataBound="ASPxGridView_DataBound">

**Comment by DominickDX** [comment]
Hello,
We haven't managed to reproduce the issue: the example project works correctly on our side.
We are happy to hear that you resolved the issue on your side. If you have any questions while starting-up this example, do not hesitate to contact us in our [Support Center] (https://www.devexpress.com/Support/Center/Question/List/1,) with the description of an occurred error. We are always ready to help you.
